### ISSUE TITLE
Fullscreen not working in Chrome iOS, should it?

### ISSUE THREAD

**Issue by kintz09** [rafrex/fscreen#20]
We are using fscreen as our cross-browser solution to make our react app go fullscreen. Its been working very well for us so far but we are running into one browser where it doesn't work, iOS (iPad) Chrome. 

We are successfully using it in Chrome, Safari, and Firefox on macOS and Windows. It also works in iOS (ipad) Safari. However, nothing happens when we request fullscreen in Chrome on iOS (ipad).

I haven't come across any documentation as to whether it should be possible to go into fullscreen in Chrome iOS on an iPad. Does anyone know if fscreen is expected to work in Chrome iOS?

**Comment by MDSilviu** [comment]
https://caniuse.com/#search=full%20screen
on ios only on ipad the full screen api it's implemented

**Comment by kintz09** [comment]
> https://caniuse.com/#search=full%20screen
> on ios only on ipad the full screen api it's implemented

CanIUse bundles compatibility for iOS Safari and iOS Chrome together under iOS Safari. This would leave me to believe Fullscreen should be supported on Safari and Chrome on iOS, however real world tests provided different results.

When I first posted this question, I had missed the nice utility this package offers to test fullscreen functionality which can be found at http://fscreen.rafrex.com/. Upon testing, I was able to confirm that Safari iOS (on iPad) supports Fullscreen and Chrome iOS (on iPad) does not. 

We are going to proceed with the assumption that Chrome iOS (on iPad) does not support fullscreen. If anyone knows how to achieve this, I'd love to learn how.

**Comment by rafrex** [comment]
Thanks for investigating this. On iOS every browser is Safari under the hood, so it's weird that Safari and Chrome differ on the iPad (maybe it's because iOS doesn't support fullscreen in 3rd party app web views, which is essentially Chrome on iOS, just a guess). I don't think this is an issue with `fscreen` but rather a lack of support/bug for the fullscreen api in Chrome iOS. I'd try reporting this to the Chrome team, since common knowledge is that all browsers on iOS are the same.
